openapi: '3.0.3'
info:
  version: 1.4.6
  title: UserGroupsController
  description: |
    <h2>Manage ldap user groups list.</h2>

servers:
  - url: http://localhost:8084
    description: For real server

tags:
  - name: Processes
    description: |
      <div>When calling with ajax, the request is "POST", except for legacy browsers.</div>
  - name: IndexPages
    description: |
      <div>The URI changes depending on the presence or absence of parameters.</div>
      <div>And Almost 'GET' requests.</div>
  - name: OtherPages
    description: (and modal pages). Almost 'GET' requests.

paths:

  /ldap-user-groups-list/ldap-user-groups-index:
    get:
      tags: ["IndexPages"]
      description: Index.
      responses:
        '200':
          description: Successful response

  /ldap-user-groups-list/ldap-user-groups-index/code_for_sub_grid/{LdapId}:
    get:
      tags: ["IndexPages"]
      description: Index.
      responses:
        '200':
          description: Successful response
    parameters:
    - $ref: "#/components/parameters/LdapId"

  /ldap-user-groups-list/ldap-user-groups-index/user_groups_ids/{MultipleUserGroupsId}:
    get:
      tags: ["IndexPages"]
      description: Index.
      responses:
        '200':
          description: Successful response
    parameters:
    - $ref: "#/components/parameters/MultipleUserGroupsId"

  /ldap-user-groups-list/ldap-user-groups-index/code_for_sub_grid/{LdapId}/user_groups_ids/{MultipleUserGroupsId}:
    get:
      tags: ["IndexPages"]
      description: Index.
      responses:
        '200':
          description: Successful response
    parameters:
    - $ref: "#/components/parameters/MultipleUserGroupsId"
    - $ref: "#/components/parameters/LdapId"

  /ldap-user-groups-list/list:
    post:
      tags: ["Processes"]
      description: Get list for index page.
      requestBody:
        description: In to ajax parameters:data.
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                page:
                  description: Page number.
                  type: integer
                  example: 0
      responses:
        '200':
          $ref: '#/components/responses/success_xml_list_for_list'

  /ldap-user-groups-list/get-sub-grid-list/:
    post:
      tags: ["Processes"]
      description: Get list for subgrid on index page.
      requestBody:
        description: In to ajax parameters:data.
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                ldap_id:
                  description: ldap_id.
                  type: string
                  example: 0006
                page:
                  description: Page number.
                  type: integer
                  example: 0
      responses:
        '200':
          $ref: '#/components/responses/success_xml_list_for_subgrid'

  /ldap-user-groups-list/sort:
    post:
      tags: ["Processes"]
      description: Reload after set sort parameters.
      requestBody:
        description: |
          <div>In to ajax parameters:data.</div>
          <div>This method changes the sort target according to the contents of the parameters.</div>
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                order:
                  description: Target column.
                  type: string
                  example: name
                direction:
                  description: direction to sort. asc | desc
                  type: string
                  example: 'asc'
                parent_code:
                  description: |
                    <div>Parent code.</div>
                    <div>If has not parent, then you must set empty value for this paramter.</div>
                    type: string
                  example: ''
      responses:
        '200':
          description: Result.
          content:
            application/xml:
              schema:
                type: object
                xml:
                  name: result # <<<
                properties:
                  message:
                    type: string
                    example: ""
                  debug:
                    type: string
                    example: ""
                  status:
                    type: integer
                    example: 1

  /ldap-user-groups-list/regist:
    get:
      tags: ["OtherPages"]
      description: Register.
      responses:
        '200':
          description: Successful response

  /ldap-user-groups-list/execregist:
    post:
      tags: ["Processes"]
      description: |
        <div>Register user group.</div>
        <h3>Attention: It can affect the results of "Code ception".</h3>
        <div>Please delete, after insert record.</div>
      requestBody:
        description: In to ajax parameters:data.
        content:
          application/ajax:
            schema:
              type: object
              properties:
                form[name]: 
                  description: User group name.
                  type: string
                  example: 'testUserGroup'
                form[comment]:
                  description: Comment.
                  type: string
                  example: ''
                isUpdate:
                  description: Is update flag.
                  type: string
                  example: '0'
      responses:
        '200':
          description: Result xml.
          content:
            application/xml:
              schema:
                type: object
                xml:
                  name: result # <<<
                properties:
                  message:
                    type: string
                    example: "登録が完了しました。"
                  debug:
                    type: string
                    example: ""
                  status:
                    type: integer
                    example: 1

  /ldap-user-groups-list/update/code/{SingleUserGroupsId}:
    get:
      tags: ["OtherPages"]
      description: Update.
      responses:
        '200':
          description: Successful response
    parameters:
    - $ref: "#/components/parameters/SingleUserGroupsId"

  /ldap-user-groups-list/execupdate:
    post:
      tags: ["Processes"]
      description: |
        <div> Update user group.</div>
        <h3>Attention: It can affect the results of "Code ception".</h3>
        <div>Please revert, after update record.</div>
      requestBody:
        description: In to ajax parameters:data.
        content:
          application/ajax:
            schema:
              type: object
              properties:
                form[name]: 
                  description: User group name.
                  type: string
                  example: 'testUserGroup'
                form[comment]:
                  description: Comment.
                  type: string
                  example: ''
                isUpdate:
                  description: Is update flag.
                  type: string
                  example: '1'
      responses:
        '200':
          description: Result xml.
          content:
            application/xml:
              schema:
                type: object
                xml:
                  name: result # <<<
                properties:
                  message:
                    type: string
                    example: "更新を完了しました。"
                  debug:
                    type: string
                    example: ""
                  status:
                    type: integer
                    example: 1

  /ldap-user-groups-list/execdelete:
    post:
      tags: ["Processes"]
      description: |
        <div>Delete user group.</div>
        <h3>Attention: It can affect the results of "Code ception".</h3>
        <div>Please delete, after create record.</div>
      requestBody:
        description: In to ajax parameters:data.
        content:
          application/ajax:
            schema:
              type: object
              properties:
                code:
                  description: user_groups.user_groups_id
                  type: string
                  example: '900004'
      responses:
        '200':
          description: Result xml.
          content:
            application/xml:
              schema:
                type: object
                xml:
                  name: result # <<<
                properties:
                  message:
                    type: string
                    example: "削除を完了しました。"
                  debug:
                    type: string
                    example: ""
                  status:
                    type: integer
                    example: 1

components:

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:

    xmllist_rows_inner_for_list:
      items:
        type: object
        properties:
          row:
            type: object
            properties:
              id:
                type: string
                example: '000003'
                xml:
                  attribute: true
              check_cell: # mean name
                type: string
                example: ''
                xml:
                  name: cell
              user_groups_name: # mean name
                type: string
                example: 'KYOTOサンプル'
                xml:
                  name: cell
              comment: # mean name
                type: string
                example: ''
                xml:
                  name: cell
              number_of_registered_users: # mean name
                type: integer
                example: 0
                xml:
                  name: cell
              spacer_cell: # mean name
                type: string
                example: ''
                xml:
                  name: cell
      xml:
        name: rows

    xmllist_rows_inner_for_subgrid_list:
      items:
        type: object
        properties:
          row:
            type: object
            properties:
              id:
                type: string
                example: '000001'
                xml:
                  attribute: true
              check_cell: # mean name
                type: string
                example: ''
                xml:
                  name: cell
              user_groups_name: # mean name
                type: string
                example: 'testUserGroup'
                xml:
                  name: cell
              comment: # mean name
                type: string
                example: ''
                xml:
                  name: cell
              number_of_registered_users: # mean name
                type: integer
                example: 0
                xml:
                  name: cell
              spacer_cell: # mean name
                type: string
                example: ''
                xml:
                  name: cell
      xml:
        name: rows

  # $ref: '#/components/responses/success_json'
  responses:
    success_json:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              custom_data:
                type: object
                properties:
                  error_code:
                    description: If the registration failed, the error code is given here. If succeeded, this is empty string.
                    type: string
                    example: ''
                  debug_messages:
                    type: object
                  error_messages:
                    type: object
                  messages:
                    description: Message for the success of the registration.
                    type: string
                    example: ''
                  status:
                    description: Whether the request succeeded or not.
                    type: boolean
                    example: true

    success_xml_list_for_list:
      description: Result xml.
      content:
        application/xml:
          schema:
            type: object
            xml:
              name: return_data # <<<
            properties:
              rows:
                type: array
                items:
                $ref: "#/components/schemas/xmllist_rows_inner_for_list"
              message:
                type: string
                example: ""
              debug:
                type: string
                example: ""
              status:
                type: integer
                example: 1
              page:
                type: integer
                example: 0
              max:
                type: integer
                example: 10
              limit:
                type: integer
                example: 50

    success_xml_list_for_subgrid:
      description: Result xml.
      content:
        application/xml:
          schema:
            type: object
            xml:
              name: return_data # <<<
            properties:
              rows:
                type: array
                items:
                $ref: "#/components/schemas/xmllist_rows_inner_for_subgrid_list"
              message:
                type: string
                example: ""
              debug:
                type: string
                example: ""
              status:
                type: integer
                example: 1
              page:
                type: integer
                example: 0
              max:
                type: integer
                example: 10
              limit:
                type: integer
                example: 50

  parameters:

    LdapId:
      name: LdapId
      in: path
      required: true
      description: Column ldap_id
      schema:
        type: string
        example: '0006'

    SingleUserGroupsId:
      name: SingleUserGroupsId
      in: path
      required: true
      description: Column user_groups.user_groups_id
      schema:
        type: string
        example: '000001'

    MultipleUserGroupsId:
      name: MultipleUserGroupsId
      in: path
      required: true
      description: Column user_groups.user_groups_id
      schema:
        type: string
        example: '000001,000007'

security:
- basicAuth: []