openapi: '3.0.3'
info:
  version: 1.4.6
  title: TermsController
  description: ''

servers:
  - url: http://localhost:8084
    description: For real server

tags:
  - name: Processes
    description: |
      <div>When calling with ajax, the request is "POST", except for legacy browsers.</div>
  - name: Pages
    description: (and modal pages). Almost 'GET' requests.

paths:

  /terms/index:
    get:
      tags: ["Pages"]
      description: Index.
      responses:
        '200':
          description: Successful response

  /terms/exec-agree:
    get:
      tags: ["Processes"]
      description: Set "agree on terms of service" parameter for session, and return process status.
      responses:
        '200':
          $ref: '#/components/responses/success_json'

components:

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  # schemas:

  # $ref: '#/components/responses/success_json'
  responses:
    success_json:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              custom_data:
                type: object
                properties:
                  error_code:
                    description: If the registration failed, the error code is given here. If succeeded, this is empty string.
                    type: string
                    example: ''
                  debug_messages:
                    type: object
                  error_messages:
                    type: object
                  messages:
                    description: Message for the success of the registration.
                    type: string
                    example: ''
                  status:
                    description: Whether the request succeeded or not.
                    type: boolean
                    example: true

security:
- basicAuth: []