<?php

class Log_API extends ExtModel
{
    protected $table = "log_rec";
    protected $primary_key = array("log_id");
    protected $foreign_key = [];

    protected $sequence = true;
    protected $count_key = 'log_id';
    protected $selectValueFieldId = 'log_id';
    protected $selectDisplayFieldId = 'application_control_name';

    protected $regist_date = 'regist_date';
    protected $update_date = 'update_date';

    protected $next_controller;
    protected $default_order = array("regist_date DESC");
    protected $search_param = array(
        'master' => array(
            'regist_date' => array('start' => '', 'end' => ''),
            'company_name' => array('ilike' => ''),
//            'user_id' => array('ilike' => ''),
            'user_name' => array('ilike' => ''),
//            'file_id' => array('ilike' => ''),
            'file_name' => array('ilike' => ''),
            'operation_id' => '',
            'application_name' => array('ilike' => ''),
 //           'mail' => array('ilike' => ''),
 //           'client_ip_global' => array('ilike' => ''),
//            'project_id' => array('ilike' => ''),
            'project_name' => array('ilike' => ''),
        ),

    );
    protected $form_param = array(
        'log_id' => '',
//        'file_id' => '',
        'file_name' => '',
        'application_name' => '',
        'company_name' => '',
//        'user_id' => '',
        'user_name' => '',
        'mail' => '',
        'client_ip_global' => '',
        'encrypts_user_id' => '',
        'encrypts_company_name' => '',
        'encrypts_user_name' => '',
        'operation_id' => '',
        'application_control_id' => '',
    );
    protected $regist_user_id = 'regist_user_id';
    protected $update_user_id = 'update_user_id';
    protected $login_user_id;

    protected $fields_master = array(
        'master' => array(
            'encrypts_user_id' => array(
                'name' => '##FIELD_NAME_ENCRYPTS_USER_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '6',
                'max' => '6',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'application_control_id' => array(
                'name' => '##FIELD_NAME_APPLICATION_CONTROL_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '5',
                'max' => '5',
                'search' => false,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'log_id' => array(
                'name' => '##FIELD_NAME_LOG_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '10',
                'max' => '10',
                'search' => false,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '0',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '',
            ),
            'file_id' => array(
                'name' => '##FIELD_NAME_FILE_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '10',
                'max' => '10',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '7',
            ),
            'file_name' => array(
                'name' => '##FIELD_NAME_FILE_NAME##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '1',
                'max' => '260',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => true,
                'col_align' => 'left',
                'col_width' => '300',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '8',
            ),
            'operation_id' => array(
                'name' => '##FIELD_NAME_OPERATION_ID##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_LOG_REC_OPERATION_ID_1##', /* ENCRYPTION */
                    '2' => '##FIELD_DATA_LOG_REC_OPERATION_ID_2##', /* FILE_OPEN */
                    '3' => '##FIELD_DATA_LOG_REC_OPERATION_ID_3##', /* SAVE */
//                    '4' => '##FIELD_DATA_LOG_REC_OPERATION_ID_4##', /* DELETE */
//                    '5' => '##FIELD_DATA_LOG_REC_OPERATION_ID_5##' ,
//                    '6' => '##FIELD_DATA_LOG_REC_OPERATION_ID_6##' ,
//                    '7' => '##FIELD_DATA_LOG_REC_OPERATION_ID_7##' ,
                    '8' => '##FIELD_DATA_LOG_REC_OPERATION_ID_8##', /* DECODE */
                    '9' => '##FIELD_DATA_LOG_REC_OPERATION_ID_9##' /* SAVE_AS */
                ),
                'min' => '1',
                'max' => '9',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => true,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '9',
            ),
            'application_name' => array(
                'name' => '##FIELD_NAME_APPLICATION_NAME##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '1',
                'max' => '260',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => true,
                'col_align' => 'left',
                'col_width' => '200',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '10',
            ),
            'user_id' => array(
                'name' => '##FIELD_NAME_USER_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '6',
                'max' => '6',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false, /* ログ管理画面で非表示カラムとして利用するためtrue */
                'col_align' => 'left',
                'col_width' => '100',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '3',
            ),
            'user_name' => array(
                'name' => '##FIELD_NAME_USER_NAME##',
                'type' => 'text',
                'ext_type' => '',
                'min' => '',
                'max' => '',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => true,
                'col_align' => 'left',
                'col_width' => '150',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '4',
            ),
            'company_name' => array(
                'name' => '##FIELD_NAME_COMPANY_NAME##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '1',
                'max' => '200',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => true,
                'col_align' => 'left',
                'col_width' => '150',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '2',
            ),
            'mail' => array(
                'name' => '##FIELD_NAME_MAIL##',
                'type' => 'text',
                'ext_type' => 'email',
                'min' => '',
                'max' => '',
                'search' => false,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '200',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '',
            ),
            'os_user' => array(
                'name' => '##FIELD_NAME_LOGON_USER##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '0',
                'max' => '64',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'os_display_user' => array(
                'name' => '##FIELD_NAME_OS_DISPLAY_USER##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '0',
                'max' => '64',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'host_name' => array(
                'name' => '##FIELD_NAME_HOST_NAME##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '0',
                'max' => '64',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'client_ip_global' => array(
                'name' => '##FIELD_NAME_CLIENT_IP_GLOBAL##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '5',
                'max' => '15',
                'search' => false,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '130',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '',
            ),
            'client_ip_local' => array(
                'name' => '##FIELD_NAME_CLIENT_IP_LOCAL##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '0',
                'max' => '15',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'mac_addr' => array(
                'name' => '##FIELD_NAME_MAC_ADDR##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '0',
                'max' => '17',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'os_version' => array(
                'name' => '##FIELD_NAME_OS_VERSION##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '0',
                'max' => '64',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'serial_no' => array(
                'name' => '##FIELD_NAME_SERIAL_NO##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '0',
                'max' => '64',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'location' => array(
                'name' => '##FIELD_NAME_LOCATION##',
                'type' => 'varchar',
                'ext_type' => '',
                'min' => '5',
                'max' => '15',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'encrypts_company_name' => array(
                'name' => '##FIELD_NAME_ENCRYPTS_COMPANY_NAME##',
                'type' => 'text',
                'ext_type' => '',
                'min' => '',
                'max' => '',
                'search' => false,
                'notnull' => false,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'encrypts_user_name' => array(
                'name' => '##FIELD_NAME_ENCRYPTS_USER_NAME##',
                'type' => 'text',
                'ext_type' => '',
                'min' => '',
                'max' => '',
                'search' => false,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'regist_date' => array(
                'name' => '##FIELD_NAME_REGIST_DATE##',
                'type' => 'timestamp',
                'ext_type' => '',
                'min' => '',
                'max' => '',
                'search' => true,
                'notnull' => true,
                'insert' => true,
                'update' => false,
                'list' => true,
                'col_list' => true,
                'col_align' => 'left',
                'col_width' => '170',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '1',
            ),
            'update_date' => array(
                'name' => '##FIELD_NAME_UPDATE_DATE##',
                'type' => 'timestamp',
                'ext_type' => '',
                'min' => '',
                'max' => '',
                'search' => false,
                'notnull' => false,
                'insert' => true,
                'update' => true,
                'list' => false,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'is_administrator' => array(
                'name' => '##FIELD_NAME_IS_ADMINISTRATOR##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '0' => '##FIELD_DATA_USER_MST_IS_ADMINISTRATOR_0##',
                    '1' => '##FIELD_DATA_USER_MST_IS_ADMINISTRATOR_1##',
                ),
                'min' => '0',
                'max' => '1',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => true,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'is_host_company' => array(
                'name' => '##FIELD_NAME_IS_HOST_COMPANY##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '0' => '##FIELD_DATA_USER_MST_IS_HOST_COMPANY_0##',
                    '1' => '##FIELD_DATA_USER_MST_IS_HOST_COMPANY_1##',
                ),
                'min' => '0',
                'max' => '1',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => true,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'has_license' => array(
                'name' => '##FIELD_NAME_HAS_LICENSE##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '0' => '##FIELD_DATA_USER_MST_HAS_LICENSE_000##',
                    '1' => '##FIELD_DATA_USER_MST_HAS_LICENSE_001##',
                ),
                'min' => '0',
                'max' => '1',
                'search' => true,
                'notnull' => false,
                'insert' => true,
                'update' => true,
                'list' => true,
                'col_list' => false,
                'col_align' => '',
                'col_width' => '',
                'col_type' => '',
                'col_sort' => '',
                'col_order' => '',
            ),
            'project_id' => array(
                'name'      => '##FIELD_NAME_PROJECT_ID##',
                'type'      => 'char',
                'ext_type'  => '',
                'min'       => '6',
                'max'       => '6',
                'search'    => false,
                'notnull'   => false,
                'insert'    => true,
                'update'    => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '115',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '5',
            ),
            'project_name' => array(
                'name'      => '##FIELD_NAME_PROJECT_NAME##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search'    => true,
                'notnull'   => false,
                'insert'    => true,
                'update'    => false,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '250',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '6',
            ),
        ),
    );


    public function __construct()
    {
//        $this->login_user_id = $this->session->login->user_id;
        $this->next_controller = [];

        parent::__construct();
    }

    public function CreateSql($alias = "master")
    {
        $select = parent::CreateSql($alias);
        return ($select);
    }

}