<?php
class Option_api extends ExtModel
{
    protected $table         = "option_mst";
    protected $primary_key   = array("option_id");
    protected $foreign_key   = array(
            );

    protected $sequence      = false;
    protected $count_key     = 'option_id';
    protected $selectValueFieldId   = 'option_id';
    protected $selectDisplayFieldId = 'operation_with_password_expiration';

    protected $regist_date   = 'regist_date';
    protected $update_date   = 'update_date';

    protected $next_controller;
    protected $default_order = array("");
    protected $search_param = array(

            );
    protected $form_param = array(
                'password_expiration_notification_enabled'    => '',
                'operation_with_password_expiration'    => '',

            );
    protected $regist_user_id = 'regist_user_id';
    protected $update_user_id = 'update_user_id';
    protected $login_user_id;

    protected $fields_master = array(
                                        'master' => array(
                                            'option_id'         => array(
                                                                            'name'      => '##FIELD_NAME_OPTION_ID##',
                                                                            'type'      => 'char',
                                                                            'ext_type'  => '',
                                                                            'min'       => '1',
                                                                            'max'       => '1',
                                                                            'search'    => false,
                                                                            'notnull'   => true,
                                                                            'insert'    => false,
                                                                            'update'    => false,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'left',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '1',
                                                                        ),
                                            'filedefender_version'     => array(
                                                                            'name'      => '##FIELD_NAME_FILEDEFENDER_VERSION##',
                                                                            'type'      => 'text',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => true,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '0',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '2',
                                                                        ),
                                            'can_use_ldap'         => array(
                                                                            'name'      => '##FIELD_NAME_CAN_USE_LDAP##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '3',
                                                                        ),
                                            'logo_login_ext'         => array(
                                                                            'name'      => '##FIELD_NAME_LOGO_LOGIN_EXT##',
                                                                            'type'      => 'text',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '0',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '4',
                                                                        ),
                                            'logo_login_e_ext'         => array(
                                                                            'name'      => '##FIELD_NAME_LOGO_LOGIN_E_EXT##',
                                                                            'type'      => 'text',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '0',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '5',
                                                                        ),
                                            'logo_header_ext'         => array(
                                                                            'name'      => '##FIELD_NAME_LOGO_HEADER_EXT##',
                                                                            'type'      => 'text',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '0',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '6',
                                                                        ),
                                            'top_background_color'         => array(
                                                                            'name'      => '##FIELD_NAME_TOP_BACKGROUND_COLOR##',
                                                                            'type'      => 'text',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '0',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '7',
                                                                        ),
                                            'header_background_color'         => array(
                                                                            'name'      => '##FIELD_NAME_HEADER_BACKGROUND_COLOR##',
                                                                            'type'      => 'text',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '0',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '8',
                                                                        ),
                                            'global_menu_background_color'         => array(
                                                                            'name'      => '##FIELD_NAME_GLOBAL_MENU_COLOR##',
                                                                            'type'      => 'text',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '0',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '8',
                                                                        ),
                                            'password_min_length'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_MIN_LENGTH##',
                                                                            'type'      => 'int',
                                                                            'ext_type'  => '',
                                                                            'min'       => '1',
                                                                            'max'       => '64',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'right',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'ron',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '9',
                                                                        ),
                                            'is_password_same_as_login_code_allowed'         => array(
                                                                            'name'      => '##FIELD_NAME_IS_PASSWORD_SAME_AS_LOGIN_CODE_ALLOWED##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_IS_PASSWORD_SAME_AS_LOGIN_CODE_ALLOWED_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_IS_PASSWORD_SAME_AS_LOGIN_CODE_ALLOWED_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '10',
                                                                        ),
                                            'password_requires_lowercase'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_REQUIRES_LOWERCASE##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_LOWERCASE_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_LOWERCASE_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '11',
                                                                        ),
                                            'password_requires_uppercase'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_REQUIRES_UPPERCASE##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_UPPERCASE_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_UPPERCASE_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '12',
                                                                        ),
                                            'password_requires_number'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_REQUIRES_NUMBER##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_NUMBER_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_NUMBER_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '13',
                                                                        ),
                                            'password_requires_symbol'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_REQUIRES_SYMBOL##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_SYMBOL_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_REQUIRES_SYMBOL_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '14',
                                                                        ),
                                            'password_expiration_enabled'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_EXPIRATION_ENABLED##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_ENABLED_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_ENABLED_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '15',
                                                                        ),
                                            'password_valid_for'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_VALID_FOR##',
                                                                            'type'      => 'int',
                                                                            'ext_type'  => '',
                                                                            'min'       => '0',
                                                                            'max'       => '360',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'right',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'ron',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '16',
                                                                        ),
                                            'password_expiration_notification_enabled'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_EXPIRATION_NOTIFICATION_ENABLED##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_NOTIFICATION_ENABLED_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_NOTIFICATION_ENABLED_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => true,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '17',
                                                                        ),
                                            'password_expired_notify_days'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_EXPIRED_NOTIFY_DAYS##',
                                                                            'type'      => 'int',
                                                                            'ext_type'  => '',
                                                                            'min'       => '0',
                                                                            'max'       => '90',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'right',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'ron',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '18',
                                                                        ),
                                            'password_expiration_warning_on_login_enabled'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_EXPIRATION_WARNING_ON_LOGIN_ENABLED##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_WARNING_ON_LOGIN_ENABLED_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_WARNING_ON_LOGIN_ENABLED_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '19',
                                                                        ),
                                            'password_expiration_email_warning_enabled'         => array(
                                                                            'name'      => '##FIELD_NAME_PASSWORD_EXPIRATION_EMAIL_WARNING_ENABLED##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '0'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_EMAIL_WARNING_ENABLED_0##' ,
                                                                                '1'    => '##FIELD_DATA_OPTION_MST_PASSWORD_EXPIRATION_EMAIL_WARNING_ENABLED_1##' ,
                                                                                ),
                                                                            'min'       => '0',
                                                                            'max'       => '1',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => false,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '20',
                                                                        ),
                                            'operation_with_password_expiration'         => array(
                                                                            'name'      => '##FIELD_NAME_OPERATION_WITH_PASSWORD_EXPIRATION##',
                                                                            'type'      => 'smallint',
                                                                            'ext_type'  => '',
                                                                            'field_data'=> array(
                                                                                '1'     => '##FIELD_DATA_OPTION_MST_OPERATION_WITH_PASSWORD_EXPIRATION_1##' ,
                                                                                '2'     => '##FIELD_DATA_OPTION_MST_OPERATION_WITH_PASSWORD_EXPIRATION_2##' ,
                                                                                ),
                                                                            'min'       => '1',
                                                                            'max'       => '2',
                                                                            'search'    => true,
                                                                            'notnull'   => false,
                                                                            'insert'    => true,
                                                                            'update'    => true,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => 'center',
                                                                            'col_width' => '50',
                                                                            'col_type'  => 'rotxt',
                                                                            'col_sort'  => 'na',
                                                                            'col_order' => '21',
                                                                        ),
                                            "can_use_password_retry_restriction"        => array(
                                                                            "name"      => "##P_SYSTEM_LOGINAUTH_027##",
                                                                            "type"      => "smallint",
                                                                            "ext_type"  => false,
                                                                            "autokey"   => false,
                                                                            "min"       => null,
                                                                            "max"       => null,
                                                                            "search"    => true,
                                                                            "notnull"   => true,
                                                                            "field_data"=> null,
                                                                            "list"      => true,
                                                                            "col_list"  => false,
                                                                            "col_align" => "",
                                                                            "col_width" => "",
                                                                            "col_type"  => "",
                                                                            "col_sort"  => "",
                                                                            "col_order" => ""
                                                                        ),
                                            "password_retry_count"                        => array(
                                                                            "name"      => "##P_SYSTEM_LOGINAUTH_037##",
                                                                            "type"      => "int",
                                                                            "ext_type"  => false,
                                                                            "autokey"   => false,
                                                                            "min"       => 1,
                                                                            "max"       => 99,
                                                                            "search"    => true,
                                                                            "notnull"   => false,
                                                                            "field_data"=> null,
                                                                            "list"      => true,
                                                                            "col_list"  => false,
                                                                            "col_align" => "",
                                                                            "col_width" => "",
                                                                            "col_type"  => "",
                                                                            "col_sort"  => "",
                                                                            "col_order" => ""
                                                                        ),
                                            "login_timeout"                                => array(
                                                                            "name"      => "##P_SYSTEM_LOGINAUTH_035##",
                                                                            "type"      => "int",
                                                                            "ext_type"  => false,
                                                                            "autokey"   => false,
                                                                            "min"       => 1,
                                                                            "max"       => 1440,
                                                                            "search"    => true,
                                                                            "notnull"   => true,
                                                                            "field_data"=> null,
                                                                            "list"      => true,
                                                                            "col_list"  => false,
                                                                            "col_align" => "",
                                                                            "col_width" => "",
                                                                            "col_type"  => "",
                                                                            "col_sort"  => "",
                                                                            "col_order" => ''
                                                                        ),
                                            "show_terms"                            => array(
                                                                            "name"      => "##P_SYSTEM_LOGINAUTH_062##",
                                                                            "type"      => "smallint",
                                                                            "ext_type"  => false,
                                                                            "min"       => 0,
                                                                            "max"       => 20,
                                                                            "search"    => true,
                                                                            "notnull"   => false,
                                                                            "list"      => true,
                                                                            "col_list"  => false,
                                                                            "col_align" => "",
                                                                            "col_width" => "",
                                                                            "col_type"  => "",
                                                                            "col_sort"  => "",
                                                                        ),
                                            'regist_date'         => array(
                                                                            'name'      => '##FIELD_NAME_REGIST_DATE##',
                                                                            'type'      => 'timestamp',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => false,
                                                                            'notnull'   => false,
                                                                            'insert'    => true,
                                                                            'update'    => false,
                                                                            'list'      => false,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '',
                                                                            'col_type'  => '',
                                                                            'col_sort'  => '',
                                                                            'col_order' => '',
                                                                        ),
                                            'update_date'         => array(
                                                                            'name'      => '##FIELD_NAME_UPDATE_DATE##',
                                                                            'type'      => 'timestamp',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => false,
                                                                            'notnull'   => false,
                                                                            'insert'    => true,
                                                                            'update'    => true,
                                                                            'list'      => false,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '',
                                                                            'col_type'  => '',
                                                                            'col_sort'  => '',
                                                                            'col_order' => '',
                                                                        ),
                                            'regist_user_id'         => array(
                                                                            'name'      => '##FIELD_NAME_REGIST_USER_ID##',
                                                                            'type'      => '',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => false,
                                                                            'notnull'   => false,
                                                                            'insert'    => true,
                                                                            'update'    => false,
                                                                            'list'      => false,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '',
                                                                            'col_type'  => '',
                                                                            'col_sort'  => '',
                                                                            'col_order' => '',
                                                                        ),
                                            'update_user_id'         => array(
                                                                            'name'      => '##FIELD_NAME_UPDATE_USER_ID##',
                                                                            'type'      => '',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => false,
                                                                            'notnull'   => false,
                                                                            'insert'    => true,
                                                                            'update'    => true,
                                                                            'list'      => false,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '',
                                                                            'col_type'  => '',
                                                                            'col_sort'  => '',
                                                                            'col_order' => '',
                                                                        ),
                                            'client_minimum_supported_version'         => array(
                                                                            'name'      => '##FIELD_NAME_CLIENT_MINIMUM_SUPPORTED_VERSION##',
                                                                            'type'      => '',
                                                                            'ext_type'  => '',
                                                                            'min'       => '',
                                                                            'max'       => '',
                                                                            'search'    => true,
                                                                            'notnull'   => true,
                                                                            'insert'    => false,
                                                                            'update'    => false,
                                                                            'list'      => true,
                                                                            'col_list'  => false,
                                                                            'col_align' => '',
                                                                            'col_width' => '',
                                                                            'col_type'  => '',
                                                                            'col_sort'  => '',
                                                                            'col_order' => '',
                                                                        ),
                                            'maximum_license_number' => array(
                                                'name'      => '##FIELD_NAME_MAXIMUM_LICENSE_NUMBER##',
                                                'type'      => 'int',
                                                'ext_type'  => '',
                                                'min'       => '',
                                                'max'       => '',
                                                'search'    => true,
                                                'notnull'   => false,
                                                'insert'    => false,
                                                'update'    => true,
                                                'list'      => true,
                                                'col_list'  => false,
                                                'col_align' => '',
                                                'col_width' => '',
                                                'col_type'  => '',
                                                'col_sort'  => '',
                                                'col_order' => '',
                                            ),
                                            'maximum_device_number_per_user' => array(
                                                'name'      => '##FIELD_NAME_MAXIMUM_DEVICE_NUMBER_PER_USER##',
                                                'type'      => 'int',
                                                'ext_type'  => '',
                                                'min'       => '',
                                                'max'       => '',
                                                'search'    => true,
                                                'notnull'   => false,
                                                'insert'    => false,
                                                'update'    => true,
                                                'list'      => true,
                                                'col_list'  => false,
                                                'col_align' => '',
                                                'col_width' => '',
                                                'col_type'  => '',
                                                'col_sort'  => '',
                                                'col_order' => '',
                                            ),

                                        ),

    );

    public function __construct() {
        $this->next_controller = array(
        
        );
        parent::__construct() ;
    }

    public function CreateSql($alias = "master"){
        $select    = parent::CreateSql($alias);
        return ($select);
    }

}