<?php
class ProjectsFilesUsers_api extends ExtModel
{
    protected $table         = "users_projects_files";
    protected $primary_key   = array("user_id", "project_id", "file_id");
    protected $foreign_key   = array(
        '01' => array(
            'master' => array('project_id')
        ),
    );

    protected $sequence      = true;
    protected $count_key     = 'file_id';
    protected $selectValueFieldId   = 'file_id';
    protected $selectDisplayFieldId = 'can_open';

    protected $regist_date   = 'regist_date';
    protected $update_date   = 'update_date';
    protected $parent_table  = 'projects';
    protected $next_controller;
    protected $default_order = array("master.user_id");

    protected $search_param = array(
        'project_id' => array('ilike' => ''),
        'file_id' => array('ilike' => ''),
        'can_open' => '',
    );
    protected $form_param = array(
        'project_id' => '',
        'file_id' => '',
        'validity_start_date'  => '',
        'validity_end_date'  => '',
        'usage_count_limit' => '',
    );
    protected $regist_user_id = 'regist_user_id';
    protected $update_user_id = 'update_user_id';
    protected $login_user_id;

    protected $fields_master = array(
        'master' => array(
            'project_id'         => array(
                'name'      => '##FIELD_NAME_PROJECT_ID##',
                'type'      => 'char',
                'ext_type'  => 'hankaku_eisu',
                'min'       => '6',
                'max'       => '6',
                'search'    => true,
                'notnull'   => true,
                'insert'    => false,
                'update'    => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => '',
                'col_width' => '',
                'col_type'  => '',
                'col_sort'  => '',
                'col_order' => '',
            ),
            'file_id'         => array(
                'name'      => '##FIELD_NAME_FILE_ID##',
                'type'      => 'char',
                'ext_type'  => 'hankaku_eisu',
                'min'       => '10',
                'max'       => '10',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '1',
            ),
            'user_id'         => array(
                'name'      => '##FIELD_NAME_USER_ID##',
                'type'      => 'char',
                'ext_type'  => 'hankaku_eisu',
                'min'       => '6',
                'max'       => '6',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            "(CASE WHEN ((upf.validity_start_date is null) = true AND (pf.validity_start_date is null) = true AND (upf.validity_end_date is null) = true AND (pf.validity_end_date is null) = true) THEN '' ELSE (CASE WHEN (upf.validity_start_date is null) = false THEN to_char(upf.validity_start_date, 'yyyy/mm/dd hh24:mi:ss') WHEN (upf.validity_start_date is null) = true AND (pf.validity_start_date is null) = false THEN to_char(pf.validity_start_date, 'yyyy/mm/dd hh24:mi:ss') ELSE '' END) || '～' || (CASE WHEN (upf.validity_end_date is null) = false THEN to_char(upf.validity_end_date, 'yyyy/mm/dd hh24:mi:ss') WHEN (upf.validity_end_date is null) = true AND (pf.validity_end_date is null) = false THEN to_char(pf.validity_end_date, 'yyyy/mm/dd hh24:mi:ss') ELSE '' END) END)"=> array(
                'alias' => 'validity_span_date',
                'name'      => '##FIELD_NAME_IS_VALIDITY_SPAN##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search'    => true,
                'notnull'   => false,
                'insert'    => true,
                'update'    => false,
                'list'      => true,
                'col_list'  => true,
                'col_align' => '',
                'col_width' => '250',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '8',
            ),
            'usage_count_limit_minus_remaining' => array(
                'name'      => '##FIELD_NAME_IS_USAGE_COUNT##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'min'       => '-99',
                'max'       => '99',
                'search'    => true,
                'notnull'   => false,
                'default'   => '0',
                'insert'    => true,
                'update'    => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '6',
            ),
            '(usage_count_limit_minus_remaining || \'回\')' => array(
                'alias'     => 'str_usage_count_limit_minus_remaining',
                'name'      => '##FIELD_NAME_IS_USAGE_COUNT##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'min'       => '-99',
                'max'       => '99',
                'search'    => true,
                'notnull'   => false,
                'default'   => '0',
                'insert'    => true,
                'update'    => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'center',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '7',
            ),
            '(CASE WHEN pf.usage_count_limit is null OR COALESCE(pf.usage_count_limit) is null OR master.usage_count_limit_minus_remaining is null OR COALESCE(master.usage_count_limit_minus_remaining) is null THEN \'未設定\' WHEN (pf.usage_count_limit - master.usage_count_limit_minus_remaining) <= 0 THEN \'0\' ELSE to_char(pf.usage_count_limit-master.usage_count_limit_minus_remaining, \'999\') || \'回まで\' END)' => array(
                'alias'     => 'usage_count_real',
                'name'      => '##FIELD_NAME_IS_USAGE_COUNT##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search'    => true,
                'notnull'   => false,
                'default'   => '0',
                'insert'    => false,
                'update'    => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '7',
            )
        ),
        'usr' => array(
            'user_id'         => array(
                'name'      => '##FIELD_NAME_USER_ID##',
                'type'      => 'char',
                'ext_type'  => 'hankaku_eisu',
                'min'       => '6',
                'max'       => '6',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'login_code'         => array(
                'name'      => '##FIELD_NAME_LOGIN_CODE##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => true,
                'list'      => true, // false,
                'col_list'  => true, // false,
                'col_align' => 'left', //'right',
                'col_width' => '120',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '3',
            ),
            'password'         => array(
                'name'      => '##FIELD_NAME_PASSWORD##',
                'type'      => 'char',
                'ext_type'  => '',
                'min'       => '1',
                'max'       => '64',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => true,
                'list'      => false,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'ldap_id'         => array(
                'name'      => '##FIELD_NAME_LDAP_ID##',
                'type'      => 'char',
                'ext_type'  => '',
                'min'       => '4',
                'max'       => '4',
                'search'    => true,
                'notnull'   => false,
                'insert'    => true,
                'update'    => true,
                'list'      => false,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),

            'is_revoked'         => array(
                'name'      => '##FIELD_NAME_IS_REVOKED##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'field_data'=> array(
                    '0'    => '##FIELD_DATA_USER_MST_IS_REVOKED_0##' ,
                    '1'    => '##FIELD_DATA_USER_MST_IS_REVOKED_1##' ,
                ),
                'min'       => '0',
                'max'       => '1',
                'search'    => true,
                'notnull'   => false,
                'insert'    => false,
                'update'    => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),

            // ユーザ名、ユーザ名かな結合
            '((CASE WHEN usr.user_name = null THEN \'\' ELSE usr.user_name END))' => array(
                'alias' => 'user_names',
                'name'      => '##FIELD_NAME_USER_NAME##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '2', //'4',
            ),
            'is_locked'         => array(
                'name'      => '##FIELD_NAME_IS_LOCKED##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'field_data'=> array(
                    '0'    => '##FIELD_DATA_USER_MST_IS_LOCKED_0##' ,
                    '1'    => '##FIELD_DATA_USER_MST_IS_LOCKED_1##' ,
                ),
                'min'       => '0',
                'max'       => '1',
                'search'    => true,
                'notnull'   => false,
                'insert'    => true,
                'update'    => true,
                'list'      => false,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'mail'         => array(
                'name'      => '##FIELD_NAME_MAIL##',
                'type'      => 'text',
                'ext_type'  => 'email',
                'min'       => '',
                'max'       => '',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => true,
                'list'      => true,
                'col_list'  => false, //true,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '5',
            ),
            'company_name'         => array(
                'name'      => '##FIELD_NAME_COMPANY_NAME##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search'    => true,
                'notnull'   => true,
                'insert'    => true,
                'update'    => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '1',
            ),
        ),
        'pf' => array(
            'project_id' => array(
                'name' => '##FIELD_NAME_PROJECT_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '6',
                'max' => '6',
                'search' => true,
                'notnull' => true,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '1',
            ),
            'file_id' => array(
                'name' => '##FIELD_NAME_FILE_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '10',
                'max' => '10',
                'search' => true,
                'notnull' => true,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '2',
            ),
            'usage_count_limit' => array(
                'name'      => '##FIELD_NAME_IS_USAGE_COUNT##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'min'       => '1',
                'max'       => '999',
                'search'    => true,
                'notnull'   => false,
                'default'   => '0',
                'insert'    => true,
                'update'    => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            )
        ),
        'vpfpg_for_get_group_names' => array(
            'project_id' => array(
                'name' => '##FIELD_NAME_PROJECT_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '6',
                'max' => '6',
                'search' => false,
                'notnull' => true,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '0',
            ),
            'file_id' => array(
                'name' => '##FIELD_NAME_FILE_ID##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '10',
                'max' => '10',
                'search' => false,
                'notnull' => true,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '2',
            ),
            'id' => array(
                'name' => '##FIELD_NAME_id##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '6',
                'max' => '6',
                'search' => false,
                'notnull' => true,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '',
            ),
            'type' => array(
                'name' => '##FIELD_NAME_TYPE##',
                'type' => 'int',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_VIEW_PROJECT_FILES_PUBLIC_GROUPS_TYPE_1##',
                    '2' => '##FIELD_DATA_VIEW_PROJECT_FILES_PUBLIC_GROUPS_TYPE_2##',
                ),
                'min' => '1',
                'max' => '2',
                'search' => true,
                'notnull' => false,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '4',
            ),
            // グループ種別（１：権限、２：ユーザー)に応じて選択元を変更する
            '(SELECT array_to_string(ARRAY(SELECT unnest(array_agg( CASE WHEN vpfpg_for_get_group_names.type = 1 THEN ( SELECT pag.name FROM projects_authority_groups AS pag WHERE pag.project_id = vpfpg_for_get_group_names.project_id AND pag.authority_groups_id = vpfpg_for_get_group_names.id ) WHEN vpfpg_for_get_group_names.type = 2 THEN ( SELECT ug.name FROM projects_user_groups AS pug LEFT JOIN user_groups AS ug ON ug.user_groups_id = pug.user_groups_id WHERE pug.project_id = vpfpg_for_get_group_names.project_id AND pug.user_groups_id = vpfpg_for_get_group_names.id ) ELSE (\'\') END ))), \',\') AS "something_groups_name" FROM view_project_files_public_groups AS vpfpg_for_get_group_names WHERE vpfpg_for_get_group_names.project_id = master.project_id AND vpfpg_for_get_group_names.file_id = master.file_id)' => array(
                'alias' => 'something_groups_name',
                'name' => '##P_PROJECTSFILES_016##',
                'type' => 'text',
                'ext_type' => '',
                'min' => '',
                'max' => '',
                'search' => true,
                'notnull' => false,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => true,
                'col_align' => 'left',
                'col_width' => '200',
                'col_type' => 'rotxt',
                'col_sort' => 'str',
                'col_order' => '3',
            ),
        ),
    );

    public function __construct() {
        $this->next_controller = array(

        );
        parent::__construct() ;
    }

    public function CreateSql($alias = "master"){
        $select = parent::CreateSql($alias);
        $select->join(
            array('usr' => 'user_mst')
            ,'usr.user_id = ' . $alias . '.user_id'
            ,$this->GetCountArr($this->fields->usr)
        );
        $select->join(
            array('pf' => 'projects_files')
            ,'pf.file_id = ' . $alias . '.file_id'
            ,$this->GetCountArr($this->fields->pf)
        );
        // 権限グループ名
        $select->join(
            array('vpfpg_for_get_group_names' => 'view_project_files_public_groups')
            ,'vpfpg_for_get_group_names.project_id = ' . $alias . '.project_id AND vpfpg_for_get_group_names.file_id = ' . $alias . '.file_id'
            ,$this->GetCountArr($this->fields->vpfpg_for_get_group_names)
        );
        return ($select);
    }

}