<?php
class User_API extends ExtModel
{
    protected $table         = "user_mst";
    protected $primary_key   = array("user_id");
    protected $foreign_key   = array(
                '01' => array(
                    'master'                => array('ldap_id'),
                    'foreign_table_id'      => array('ldap_mst'),
                    'foreign_key_fields_id' => array('ldap_id'),
                ),
            );

    protected $sequence      = true;
    protected $count_key     = 'user_id';
    protected $selectValueFieldId   = 'user_id';
    protected $selectDisplayFieldId = 'regist_user_name';

    protected $regist_date   = 'regist_date';
    protected $update_date   = 'update_date';

    protected $next_controller;
    protected $default_order = array("user_kana");
    protected $search_param = array(
        'master' => array(
            'user_name' => array('ilike' => ''),
            'user_kana' => array('ilike' => ''),
            'has_license' => '',
            'mail' => array('ilike' => ''),
            'company_name' => array('ilike' => ''),
            'is_host_company' => '',
            'is_locked' => '',
            'language_id' => ''
        )
    );
    protected $form_param = array(
        'login_code' => '',
        'password' => '',
        'user_name' => '',
        'user_kana' => '',
        'mail' => '',
        'has_license' => '',
        'is_host_company' => '',
        'company_name' => '',
        'language_id' => ''
    );
    protected $regist_user_id = 'regist_user_id';
    protected $update_user_id = 'update_user_id';
    protected $login_user_id;
    protected $delete_key = 'is_revoked';

    protected $fields_master = array(
        'master' => array(
            'user_id' => array(
                'name'      => '##FIELD_NAME_USER_ID##',
                'type'      => 'char',
                'ext_type'  => 'hankaku_eisu',
                'min'       => '6',
                'max'       => '6',
                'search' => true,
                'notnull'   => true,
                'insert' => true,
                'update' => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'login_code' => array(
                'name'      => '##FIELD_NAME_LOGIN_CODE##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => true,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'right',
                'col_width' => '50',
                'col_type'  => 'ron',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'password' => array(
                'name'      => '##FIELD_NAME_PASSWORD##',
                'type'      => 'char',
                'ext_type'  => '',
                'min'       => '1',
                'max'       => '64',
                'search' => true,
                'notnull'   => true,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'ldap_id' => array(
                'name'      => '##FIELD_NAME_LDAP_ID##',
                'type'      => 'char',
                'ext_type'  => '',
                'min'       => '4',
                'max'       => '4',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'password_change_date' => array(
                'name'      => '##FIELD_NAME_PASSWORD_CHANGE_DATE##',
                'type'      => 'timestamp',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'is_revoked' => array(
                'name'      => '##FIELD_NAME_IS_REVOKED##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'field_data'=> array(
                    '0' => '##FIELD_DATA_USER_MST_IS_REVOKED_0##' ,
                    '1' => '##FIELD_DATA_USER_MST_IS_REVOKED_1##' ,
                ),
                'min'       => '0',
                'max'       => '1',
                'search' => true,
                'notnull'   => false,
                'insert' => false,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'onetime_password_url' => array(
                'name'      => '##FIELD_NAME_ONETIME_PASSWORD_URL##',
                'type'      => 'char',
                'ext_type'  => 'hankaku_eisu_kigo',
                'min'       => '64',
                'max'       => '64',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '0',
            ),
            'onetime_password_time' => array(
                'name'      => '##FIELD_NAME_ONETIME_PASSWORD_TIME##',
                'type'      => 'timestamp',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'is_host_company' => array(
                'name'      => '##FIELD_NAME_IS_HOST_COMPANY##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'field_data'=> array(
                    '0' => '##FIELD_DATA_USER_MST_IS_HOST_COMPANY_0##' ,
                    '1' => '##FIELD_DATA_USER_MST_IS_HOST_COMPANY_1##' ,
                    ),
                'min'       => '0',
                'max'       => '1',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'send_inviting_mail' => array(
                'name'      => '##FIELD_NAME_SEND_INVITING_MAIL##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'field_data'=> array(
                    '0' => '##FIELD_DATA_USER_MST_SEND_INVITING_MAIL_0##' ,
                    '1' => '##FIELD_DATA_USER_MST_SEND_INVITING_MAIL_1##' ,
                    ),
                'min'       => '0',
                'max'       => '1',
                'search' => false,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type'  => 'rotxt',
                'col_sort'  => 'na',
                'col_order' => '0',
            ),
            'user_name' => array(
                'name'      => '##FIELD_NAME_USER_NAME##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => true,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '200',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '1',
            ),
            'user_kana' => array(
                'name'      => '##FIELD_NAME_USER_KANA##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '200',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '2',
            ),
            'is_locked' => array(
                'name'      => '##FIELD_NAME_IS_LOCKED##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'field_data'=> array(
                    '0' => '##FIELD_DATA_USER_MST_IS_LOCKED_0##' ,
                    '1' => '##FIELD_DATA_USER_MST_IS_LOCKED_1##' ,
                    ),
                'min'       => '0',
                'max'       => '1',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'center',
                'col_width' => '100',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '4',
            ),
            'has_license' => array(
                'name'      => '##FIELD_NAME_HAS_LICENSE##',
                'type'      => 'smallint',
                'ext_type'  => '',
                'field_data'=> array(
                    '0' => '##FIELD_DATA_USER_MST_HAS_LICENSE_000##' ,
                    '1' => '##FIELD_DATA_USER_MST_HAS_LICENSE_001##' ,
                    ),
                'min'       => '0',
                'max'       => '1',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'center',
                'col_width' => '90',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '5',
            ),
            'mail' => array(
                'name'      => '##FIELD_NAME_MAIL##',
                'type'      => 'text',
                'ext_type'  => 'email',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => true,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '250',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '6',
            ),
            'company_name' => array(
                'name'      => '##FIELD_NAME_COMPANY_NAME##',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => true,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '200',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '7',
            ),
            'regist_date' => array(
                'name'      => '##FIELD_NAME_REGIST_DATE##',
                'type'      => 'timestamp',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => true,
                'notnull'   => false,
                'insert' => true,
                'update' => false,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'center',
                'col_width' => '170',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '9',
            ),
            'last_login_date' => array(
                'name'      => '##FIELD_NAME_LAST_LOGIN_DATE##',
                'type'      => 'timestamp',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => false,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'center',
                'col_width' => '170',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '10',
            ),
            "login_mistake_count" => array(
                "name"      => "##パスワード誤認証回数##",
                "type"      => "varchar",
                "ext_type"  => false,
                "min"       => false,
                "max"       => false,
                "search"    => true,
                "notnull"   => false,
                "list"      => true,
                "col_list"  => false,
                "col_align" => "",
                "col_width" => "",
                "col_type"  => "",
                "col_sort"  => "",
            ),
            'regist_user_id' => array(
                'name'      => '##FIELD_NAME_REGIST_USER_ID##',
                'type'      => 'char',
                'ext_type'  => '',
                'min'       => '6',
                'max'       => '6',
                'search' => false,
                'notnull'   => false,
                'insert' => true,
                'update' => false,
                'list'      => true,
                'col_list'  => false,
                'col_align' => '',
                'col_width' => '',
                'col_type'  => '',
                'col_sort'  => 'false',
                'col_order' => '',
            ),
            'update_date'         => array(
                'name'      => '##FIELD_NAME_UPDATE_DATE##',
                'type'      => 'timestamp',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => false,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => false,
                'col_list'  => false,
                'col_align' => '',
                'col_width' => '',
                'col_type'  => '',
                'col_sort'  => '',
                'col_order' => '',
            ),
            'update_user_id'         => array(
                'name'      => '##FIELD_NAME_UPDATE_USER_ID##',
                'type'      => 'char',
                'ext_type'  => '',
                'min'       => '6',
                'max'       => '6',
                'search' => false,
                'notnull'   => false,
                'insert' => true,
                'update' => true,
                'list'      => false,
                'col_list'  => false,
                'col_align' => '',
                'col_width' => '',
                'col_type'  => '',
                'col_sort'  => '',
                'col_order' => '',
            ),
            'auth_id'                 => array(
                'name' => '##MENU_PROJECTS_AUTHORITY_GROUPS##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '3',
                'max' => '3',
                'search' => false,
                'notnull' => true,
                'insert' => true,
                'update' => true,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '1',
            ),
            // #1577
            'language_id' => [
                'name' => '##FIELD_NAME_NOTIFICATION_EMAIL_LANGUAGE##',
                'type' => 'char',
                'ext_type' => '',
                'min' => '2',
                'max' => '2',
                'search' => false,
                'notnull' => true,
                'insert' => true,
                'update' => true, // @NOTE 20210215 true で良いとのこと。
                'list' => true,
                'col_list' => false,  // @NOTE 20210215 一覧には不要とのこと。
                'col_align' => 'left',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '11',
            ],
        ),
        'um' => array(
            'user_name'         => array(
                'name'      => '##FIELD_NAME_REGIST_USER_ID##',
                'alias'     => 'regist_user_name',
                'type'      => 'text',
                'ext_type'  => '',
                'min'       => '',
                'max'       => '',
                'search' => false,
                'notnull'   => false,
                'insert' => false,
                'update' => false,
                'list'      => true,
                'col_list'  => true,
                'col_align' => 'left',
                'col_width' => '200',
                'col_type'  => 'rotxt',
                'col_sort'  => 'str',
                'col_order' => '8',
            ),
        ),
        "auth" => array(
            'auth_name' => array(
                'name' => '##FIELD_NAME_AUTH_NAME##',
                'type' => 'text',
                'ext_type' => '',
                'min' => '',
                'max' => '',
                'search' => false,
                'notnull' => false,
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '300',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '2',
            ),
            'level' => array(
                'name' => '##FIELD_NAME_LEVEL##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_AUTH_LEVEL_1##',
                    '2' => '##FIELD_DATA_AUTH_LEVEL_2##',
                    '3' => '##FIELD_DATA_AUTH_LEVEL_3##',
                    '4' => '##FIELD_DATA_AUTH_LEVEL_4##',
                    '5' => '##FIELD_DATA_AUTH_LEVEL_5##',
                ),
                'min' => '1',
                'max' => '5',
                'search' => false,
                'notnull' => false,
                'default' => '1',
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'left',
                'col_width' => '100',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '5',
            ),
            'can_set_system' => array(
                'name' => '##FIELD_NAME_CAN_SET_SYSTEM##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_AUTH_CAN_SET_SYSTEM_1##',
                    '9' => '##FIELD_DATA_AUTH_CAN_SET_SYSTEM_9##',
                ),
                'min' => '1',
                'max' => '9',
                'search' => false,
                'notnull' => false,
                'default' => '1',
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '6',
            ),
            'can_set_user' => array(
                'name' => '##FIELD_NAME_CAN_SET_USER##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_AUTH_CAN_SET_USER_1##',
                    '5' => '##FIELD_DATA_AUTH_CAN_SET_USER_5##',
                    '7' => '##FIELD_DATA_AUTH_CAN_SET_USER_7##',
                    '8' => '##FIELD_DATA_AUTH_CAN_SET_USER_8##',
                    '9' => '##FIELD_DATA_AUTH_CAN_SET_USER_9##',
                ),
                'min' => '1',
                'max' => '9',
                'search' => false,
                'notnull' => false,
                'default' => '1',
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '7',
            ),
            'can_set_user_group' => array(
                'name' => '##FIELD_NAME_CAN_SET_USER_GROUP##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_AUTH_CAN_SET_USER_GROUP_1##',
                    '9' => '##FIELD_DATA_AUTH_CAN_SET_USER_GROUP_9##',
                ),
                'min' => '1',
                'max' => '9',
                'search' => false,
                'notnull' => false,
                'default' => '1',
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '8',
            ),
            'can_set_project' => array(
                'name' => '##FIELD_NAME_CAN_SET_PROJECT##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_AUTH_CAN_SET_PROJECT_1##',
                    '5' => '##FIELD_DATA_AUTH_CAN_SET_PROJECT_5##',
                    '9' => '##FIELD_DATA_AUTH_CAN_SET_PROJECT_9##',
                ),
                'min' => '1',
                'max' => '9',
                'search' => false,
                'notnull' => false,
                'default' => '1',
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '9',
            ),
            'can_browse_file_log' => array(
                'name' => '##FIELD_NAME_CAN_BROWSE_FILE_LOG##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_AUTH_CAN_BROWSE_FILE_LOG_1##',
                    '3' => '##FIELD_DATA_AUTH_CAN_BROWSE_FILE_LOG_3##',
                    '5' => '##FIELD_DATA_AUTH_CAN_BROWSE_FILE_LOG_5##',
                    '9' => '##FIELD_DATA_AUTH_CAN_BROWSE_FILE_LOG_9##',
                ),
                'min' => '1',
                'max' => '9',
                'search' => false,
                'notnull' => false,
                'default' => '1',
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '10',
            ),
            'can_browse_browser_log' => array(
                'name' => '##FIELD_NAME_CAN_BROWSE_BROWSER_LOG##',
                'type' => 'smallint',
                'ext_type' => '',
                'field_data' => array(
                    '1' => '##FIELD_DATA_AUTH_CAN_BROWSE_BROWSER_LOG_1##',
                    '3' => '##FIELD_DATA_AUTH_CAN_BROWSE_BROWSER_LOG_3##',
                    '9' => '##FIELD_DATA_AUTH_CAN_BROWSE_BROWSER_LOG_9##',
                ),
                'min' => '1',
                'max' => '9',
                'search' => false,
                'notnull' => false,
                'default' => '1',
                'insert' => false,
                'update' => false,
                'list' => true,
                'col_list' => false,
                'col_align' => 'center',
                'col_width' => '50',
                'col_type' => 'rotxt',
                'col_sort' => 'na',
                'col_order' => '11',
            ),
        ),
    );

    public function __construct($register_user_data=null)
    {
        parent::__construct($register_user_data);
    }

    public function CreateSql($alias = "master")
    {
        $select    = parent::CreateSql($alias);
        $select->join(
            array('um' => 'user_mst')
            ,"{$alias}.regist_user_id = um.user_id"
            ,$this->GetCountArr($this->fields->um)
        );
        $select->join(
            array("auth" => "auth")
            ,"{$alias}.auth_id = auth.auth_id"
            ,$this->GetCountArr($this->fields->auth)
        );
        return ($select);
    }

}