<?php


/**
 * @SuppressWarnings(PHPMD)
*/
class AcceptanceSettingsSetSslTester extends AcceptanceSettingsTester
{
    use _generated\AcceptanceTesterActions;

    public $currentForms = [
        'publishCsr' => [
            [
                'nameJp' => '国名',
                'name' => 'form[csr][countryName]'
            ], [
                'nameJp' => '都道府県名',
                'name' => 'form[csr][stateOrProvinceName]'
            ], [
                'nameJp' => '市区町村名',
                'name' => 'form[csr][localityName]'
            ], [
                'nameJp' => '企業名 / 組織名',
                'name' => 'form[csr][organizationName]'
            ], [
                'nameJp' => '組織単位名',
                'name' => 'form[csr][organizationalUnitName]'
            ], [
                'nameJp' => 'コモンネーム',
                'name' => 'form[csr][commonName]'
            ], [
                'nameJp' => 'メールアドレス',
                'name' => 'form[csr][emailAddress]'
            ]
        ],
        'forInstall' => [
            [
                'nameJp' => '証明書',
                'name' => 'form[ssl][crt]'
            ], [
                'nameJp' => '秘密鍵',
                'name' => 'form[ssl][key]'
            ]
        ]
    ];
    public $invalidCharacters_forSetSsl = ['"', '#', ';', '+'];

    public $currentErrorSentence_allInvalidChar = '';
    public $currentErrorSentence_emptyInstallCsr = '';

    public function construct()
    {
        parent::construct(); // TODO: Change the autogenerated stub
        $I = $this;
        $I->currentErrorSentence_allInvalidChar =<<<EOF
国名は半角英数字もしくは「"#;+」を除く記号で入力してください。
都道府県名は半角英数字もしくは「"#;+」を除く記号で入力してください。
市区町村名は半角英数字もしくは「"#;+」を除く記号で入力してください。
企業名 / 組織名は半角英数字もしくは「"#;+」を除く記号で入力してください。
組織単位名は半角英数字もしくは「"#;+」を除く記号で入力してください。
コモンネームは半角英数字もしくは「"#;+」を除く記号で入力してください。
メールアドレスの形式が不正です。
EOF;
        $I->currentErrorSentence_emptyInstallCsr =<<<EOF
証明書を入力してください。
秘密鍵を入力してください。
中間証明書を入力してください。
EOF;
    }

    /**
     * @param array $_params
     */
    public function _checkClickToError_onSettingsSetSsl($_params=[])
    {
        $I = $this;
        $I->comment($_params['description'] . 'を行った際のエラーメッセージ出力確認');
        $I->writeSubjectComment($_params['subject'] . ' クリック');
        $I->click($_params['buttonSelector']);
        $I->see('新規登録しますか？', '.dhtmlx_popup_text span');
        $I->wait($I->waitNum);
        $I->writeChildSubjectComment('はい をクリック');
        $I->click('//div[@result="true"]');
        $I->dontSee('新規登録しますか？', '.dhtmlx_popup_text span');
        if ($_params['type'] == 'currentErrorSentence_allInvalidChar') {
            $I->checkDisplayError_andClickOk($I->currentErrorSentence_allInvalidChar);
        } else {
            $I->checkDisplayError_andClickOk($I->currentErrorSentence_emptyInstallCsr);
        }
    }
}
