<?php


/**
 * @SuppressWarnings(PHPMD)
*/
class AcceptanceSettingsSetNetworkTester extends AcceptanceSettingsTester
{
    use _generated\AcceptanceTesterActions;

    public $formElements_forSetNetwork = [];

    public function construct()
    {
        $I = $this;
        parent::construct(); // TODO: Change the autogenerated stub
                    //html/body/div[2]/div[2]/div[2]/div/form[3]/table/tbody/tr[2]/td[2]/label[1]
        $pattern = '//html/body/div[2]/div[2]/div[2]/div/form[%d]/table/tbody/tr';
        $_xPathPrefix1 = sprintf($pattern, 3);//'//html/body/div[2]/div[2]/div[2]/div/form[3]/table/tbody/tr';
        $_xPathPrefix2 = sprintf($pattern, 4);
        $_xPathPrefix3 = sprintf($pattern, 5);//'//html/body/div[2]/div[2]/div[2]/div/form[5]/table/tbody/tr';
        $I->formElements_forSetNetwork = [
            'ネットワーク設定1' => [
                'IPアドレス/サブネットマスク' => [
                    [
                        'name' => 'form[network_setting1][ip_address]',
                        'type' => 'text'
                    ],
                    [
                        'name' => 'form[network_setting1][netmask]',
                        'type' => 'text'
                    ],
                ],
                'ゲートウェイ' => [
                    [
                        'name' => 'form[network_setting1][gateway]',
                        'type' => 'text'
                    ],
                ],
                'プライマリDNS' => [
                    [
                        'name' => 'form[network_setting1][primary_dns]',
                        'type' => 'text'
                    ],
                ],
                'セカンダリDNS' => [
                    [
                        'name' => 'form[network_setting1][secondary_dns]',
                        'type' => 'text'
                    ]
                ]
            ],
            'ネットワーク設定2' => [
                'ネットワーク設定2の利用' => [
                    [
                        'name' => 'form[network_setting2][use_flag]',
                        'values' => [
                            [
                                'value' => '1',
                                'xPathLabel' => $_xPathPrefix1 . '[1]/td[2]/label[1]',
                                'xPath' => $_xPathPrefix1 . '[1]/td[2]/label[1]/input',
                                'label' => '使用しない'
                            ],[
                                'value' => '2',
                                'xPathLabel' => $_xPathPrefix1 . '[1]/td[2]/label[2]',
                                'xPath' => $_xPathPrefix1 . '[1]/td[2]/label[2]/input',
                                'label' => '使用する'
                            ]
                        ],
                        'type' => 'radio'
                    ]
                ],
                'IPアドレス/サブネットマスク' => [
                    [
                        'name' => 'form[network_setting2][ip_address]',
                        'xPath' => $_xPathPrefix1 . '[2]/td[2]/input[1]',
                        'type' => 'text'
                    ],
                    [
                        'name' => 'form[network_setting2][netmask]',
                        'xPath' => $_xPathPrefix1 . '[2]/td[2]/input[2]',
                        'type' => 'text'
                    ],
                ],
                'ゲートウェイ' => [
                    [
                        'name' => 'form[network_setting2][gateway]',
                        'xPath' => $_xPathPrefix1 . '[3]/td[2]/input',
                        'type' => 'text'
                    ],
                ],

            ],
            'NTPサーバー設定' => [
                'NTPサーバー' => [
                    [
                        'name' => 'form[ntp_server]',
                        'xPath' => $_xPathPrefix2 . '/td[2]/textarea',
                        'type' => 'textarea'
                    ]
                ]
            ],
            'メールサーバー設定' => [
                'ホスト名' => [
                    [
                        'name' => 'form[mail_server][mail_relay_use_flag]',
                        'values' => [
                            [
                                'value' => '1',
                                'xPathLabel' => $_xPathPrefix3 . '[2]/td[2]/label[1]',
                                'xPath' => $_xPathPrefix3 . '[2]/td[2]/label[1]/input',
                                'label' => '使用しない'
                            ],[
                                'value' => '2',
                                'xPathLabel' => $_xPathPrefix3 . '[2]/td[2]/label[2]',
                                'xPath' => $_xPathPrefix3 . '[2]/td[2]/label[2]/input',
                                'label' => '使用する'
                            ]
                        ],
                        'type' => 'radio'
                    ]
                ],
                'メールリレー先' => [
                    [
                        'name' => 'form[mail_server][relay_host]',
                        'xPath' => $_xPathPrefix3 . '[2]/td[2]/input',
                        'type' => 'text'
                    ]
                ]
            ]
        ];
    }
}
