= users_projects_files テーブルカスケードテスト手順書
横矢 <t-yokoya@plott.co.jp>


== 概要
テーブルカスケードテストの手順を記す。

=== テストケースの表記
各テストケースに大番号（例では大文字アルファベットであらわす）および小番号（例では小文字アルファベットであらわす）を割り振り、

"テストM_n"

というように表記する。

== テストファイル内容
テーブル環境作成.sql と テスト状態表・テストケース.xlsx の二つ。

=== テーブル環境作成.sql
テスト初期状態（操作を実行する前の DB テーブル状態）を作成する sql ファイル。

=== テスト状態表・テストケース.xlsx
テスト内容を記載。

==== テーブル状態表シート
各テスト初期状態のテーブル内容を表す。

* 各状態に大番号を割り当てている。
* 状態 M では users_projects_files テーブルにおいて、「ユーザーM」が「テストプロジェクトM」内の「ファイルM」と結びついているレコード（テストレコード）が存在する。テスト操作後にこのレコードが残っているか消えているかをチェックする。
* 状態 M での他のエンティティ（ユーザーグループ、権限グループ）の名前に付随する番号は、エンティティが一つなら M, 二つなら M と M+100 となっている。

==== テストケース
各テストケースで行う操作と実現されるべき結果を記載している。

* 各操作（何かの削除操作）に小番号を割り当てている。

操作結果は

* -：そもそも削除対象がなかったり、（仕様上の）エラーが表示されるなどして操作を行うことができない
* T：操作後にもテストレコードが残っている
* F：操作に伴いテストレコードが消滅する

== テスト手順
IMPORTANT: user_idが1であるユーザー1（初期ユーザー扱い）はデフォルトでは削除できないので fd_define.php ADMIN_USER_ID の数値を適当に変えておく。

各小番号について下記手順を行う（下は例として小番号 n の場合）。

IMPORTANT: テストケース52以降については少し特殊なので後の補足ｗ参照すること。

. データベースに テーブル環境作成.sql を適用する。
. テスト状態表・テストケース.xlsx テストケースシート内の小番号 n に相当する削除対象を確認する。
. 各大番号について下記手順を行う（下は例として大番号 M の場合）。
.. テスト状態表・テストケース.xlsx テストケースシート内の テストM_n に相当するセル内容を確認する（- か T か F）。
... 「-」であるとき、WEB 上から対象項目を削除することができない（項目がなかったり、エラーが表示される）ことを確認する。確認できたときは、該当する項目の結果を「〇」、削除することが可能であった場合は結果を「×」とする。
... 「-」でないとき、WEB 上から対象項目の削除を行えることを確認し、削除を行う。削除することができない場合は、該当項目の結果を「×」とする。これらを右の結果に記録する。
. DB 上の users_projects_files テーブルを確認し、残っているレコードを確認する。
. テスト状態表・テストケース.xlsx テストケースシート内で「T」となっている大番号に相当するレコード（例えば大番号 M ならば user_id = project_id = file_id = M のレコード）のみがテーブルに残っていることを確認する。正しい結果には「〇」、本来残っているべきレコードが消えている場合、本来消えているべきレコードが残っている場合は「×」と右の結果に記録する。

IMPORTANT: テストケース52以降（52-52, 52-152, 152-152）について。これらは他の（ユーザーとファイルが結びついているものと関係ない）リレーションが存在していても影響されないことを確認するための確認ケースである。users_projects_files にユーザー52, 152とファイル52,152の4つの組み合わせのレコードがあるのでそれらについて挙動をみる。

== テーブル状態表について
=== テーブル状態表(大番号1-51)について
数字はエンティティ間の関係（1対1→11, 1対2→12, 2対1→21, 2対2→22）をあらわす。2対2は独立した1対1が2つ存在する関係をあらわす。

=== テーブル状態表(大番号52以降)について
関係するリレーションのレコードの一覧をあらわしている。