= users_projects_files テーブルカスケードテスト計画書
横矢 <t-yokoya@plott.co.jp>

== 文書番号
未割当（割り当てるべき）

== レファレンス
* テスト手順書.adoc
* テーブル環境作成.sql
* テスト状態表・テストケース.xlsx

== 概要
ver.1.4.3 より新たに追加された users_projects_files テーブルのカスケード部分をデータベース上でなくソース上で実装することとなった。本テストはその動作を対象としている。

== テストアイテム
File Defender サーバー ver.1.4.3

== テストするべき機能
users_projects_files テーブルのレコードの削除を引き起こす動作を行ったときに、確かに消えるべきレコードが消えていることをテストする。

== テストする必要のない機能
削除以外の機能（作成、更新）についてはテストしない。WEB 画面も操作が可能かどうかのみをチェックし、文言表示や挙動についてはテストしない。

CAUTION: テストデータ作成時の都合により、一部 word_mst の表記がおかしいところがあるが、今回のテストには無関係であるから無視すること。

== アプローチ
ブラックボックス技法を用いる。

できるだけ多くの可能性をカバーした初期のテスト状態（特定のユーザーが何らかのリレーションのつながりによって特定のファイルと結びつき、users_projects_files テーブルにレコードが存在する状態）を用意する。各状態に対して、実行可能な削除操作（エンティティの削除やリレーションの削除）を行ったときに関連した users_projects_files 上のレコードが消えるべきかどうかをあらかじめテストケースとして用意しておき、実際に行った際に想定通りの挙動となるかをテストする。

== テストアイテムの合否判定基準
* 想定通り、削除操作をそもそも行えない

* 想定通り、削除操作を行ったときに関連した users_projects_files 上のレコードが削除されている

* 想定通り、削除操作を行ったときに関連した users_projects_files 上のレコードが削除されていない

== 終了基準
テスト実行者全員について（テストケースそのものが問題あるとされて）保留されていたものを除いたテストケースが全て合格となったとき

== 中止基準と再開要件
* テストケースそのものに問題があることが判明したとき。問題の原因が取り除かれ、テストケースが修正されたときに再開する。

* 優先度の関係からテストマネージャが中止を決定したとき

== テスト成果物
テスト結果の書き込まれた テスト状態表・テストケース.xlsx

ファイル名は「xxxx_xx_xxテスト結果_〇〇.xlsx」とする。xxxx_xx_xx は年月日、〇〇はテスト実行者の苗字（同姓がいる場合は名前も）

== テスティングタスク
テスト手順書を参照

== 実行環境
？？？

== 人員計画、トレーニングプラン
？？？

== スケジュール
いつやるの？

== 承認
なし